# 系统配置
system:
  db-type: "mysql"

# MySQL 配置
mysql:
  path: "43.139.116.74"
  port: "3306"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "toma-photo"
  username: "root"
  password: "fanqie"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
  