# 系统配置
system:
  env: develop
  addr: 9999
  db-type: "mysql"
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  # IP限制一个小时
  iplimit-time: 3600
  router-prefix: ""

# MySQL 配置
mysql:
  path: "43.139.116.74"
  port: "3306"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "toma-photo"
  username: "root"
  password: "fanqie"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# zap logger configuration
zap:
  level: debug
  format: json
  prefix: ""
  director: log
  show-line: true
  max-age: 14
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  