info:
  contact: {}
paths:
  /health:
    get:
      description: 心跳检测aaa
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 心跳检测
      tags:
      - basic
swagger: "2.0"
